#!/bin/sh
set -e

case "$1" in
  remove|deconfigure)
    if [ -d /run/systemd/system ]; then
      systemctl stop cobraagent.service || true
      systemctl disable cobraagent.service || true
    fi
    ;;
esac

exit 0
